apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tetragon.fullname" . }}-config
  namespace: {{ include "tetragon.namespace" . }}
  labels:
    {{- include "tetragon.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml .Values.config | nindent 2 }}
