{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "tetragon.fullname" . }}
  namespace: {{ include "tetragon.namespace" . }}
  labels:
    {{- include "tetragon.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  limits:
    {{- toYaml .Values.limitRange.limits | nindent 4 }}
{{- end }}
