{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tetragon.serviceAccountName" . }}
  namespace: {{ include "tetragon.namespace" . }}
  labels:
    {{- include "tetragon.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
