apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubearmor
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: security-stack
spec:
  interval: 12h
  url: https://kubearmor.github.io/charts/
